FROM ubuntu:18.04

WORKDIR /home/app

RUN apt-get update

RUN apt-get install --yes curl
RUN curl --silent --location https://deb.nodesource.com/setup_12.x | bash -
RUN apt-get install --yes nodejs
RUN apt-get install --yes build-essential
RUN apt-get install --yes build-essential
RUN apt  install --yes golang-go 
RUN mkdir /usr/app
RUN mkdir /usr/app/log

COPY  ./API/. /expressapp/.

ENV APPPORTID=1111
RUN cd /expressapp/; npm install; npm i -g nodemon;

EXPOSE 1111

CMD ["nodemon", "/expressapp/index.js"]